Name:           ros-indigo-cob-controller-configuration-gazebo
Version:        0.6.1
Release:        0%{?dist}
Summary:        ROS cob_controller_configuration_gazebo package

Group:          Development/Libraries
License:        LGPL
URL:            http://ros.org/wiki/cob_controller_configuration_gazebo
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-cob-bringup
Requires:       ros-indigo-cob-cam3d-throttle
Requires:       ros-indigo-cob-control-mode-adapter
Requires:       ros-indigo-cob-frame-tracker
Requires:       ros-indigo-cob-phidgets
Requires:       ros-indigo-cob-script-server
Requires:       ros-indigo-cob-sick-s300
Requires:       ros-indigo-cob-sound
Requires:       ros-indigo-cob-twist-controller
Requires:       ros-indigo-controller-manager
Requires:       ros-indigo-effort-controllers
Requires:       ros-indigo-gazebo-ros-control
Requires:       ros-indigo-joint-state-controller
Requires:       ros-indigo-robot-state-publisher
Requires:       ros-indigo-rostopic
Requires:       ros-indigo-schunk-simulated-tactile-sensors
Requires:       ros-indigo-topic-tools
Requires:       ros-indigo-velocity-controllers
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-roslaunch

%description
This packages provides the controller configuration for simulating Care-O-bot in
the gazebo simulator.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 21 2014 Florian Weisshardt <fmw@ipa.fhg.de> - 0.6.1-0
- Autogenerated by Bloom

